drop table sensores cascade constraints;

create table sensores (
  sensor_id number generated by default on null as identity,
  timestamp date not null,
  humidity number,
  temperature number,
  ph number,
  phosphorus varchar2(50),
  potassium varchar2(50),
  irrigationOn number(1),
  constraint sensores_pk primary key (sensor_id)
);

comment on column sensores.sensor_id is 'Identificador único de cada leitura de sensor.';
comment on column sensores.timestamp is 'Data e hora em que a leitura foi registrada.';
comment on column sensores.humidity is 'Umidade relativa do solo/ar, capturada pelo sensor.';
comment on column sensores.temperature is 'Temperatura ambiente medida.';
comment on column sensores.ph is 'Medida do pH do solo (acidez/alcalinidade).';
comment on column sensores.phosphorus is 'Quantidade de fósforo, em formato texto (possivelmente categorizado).';
comment on column sensores.potassium is 'Quantidade de potássio, também em formato categórico.';
comment on column sensores.irrigationOn is 'Indicador binário: 1 = irrigação ativada, 0 = desligada.';

-- endpoint REST => https://g12bbd4aea16cc4-orcl1.adb.ca-toronto-1.oraclecloudapps.com/ords/fiap/sensores/

drop table usuarios cascade constraints;

create table usuarios (
  id number generated by default on null as identity,
  usuario varchar2(30) not null,
  senha varchar2(30) not null,
  nome_completo varchar2(128) not null,
  email varchar2(128) not null,
  ativo varchar2(1) not null, -- S -> SIM, N -> NAO
  constraint usuarios_pk primary key (id),
  constraint usuarios_uq1 unique (usuario)
);

-- endpoint REST => https://g12bbd4aea16cc4-orcl1.adb.ca-toronto-1.oraclecloudapps.com/ords/fiap/usuarios/

drop table culturas cascade constraints;

create table culturas (
  id number generated by default on null as identity,
  nome varchar2(30) not null,
  clima_ideal varchar2(128) not null,
  solo_ideal varchar2(128) not null,
  duracao_plantio varchar2(128) not null,
  constraint culturas_pk primary key (id)
);

-- endpoint REST => https://g12bbd4aea16cc4-orcl1.adb.ca-toronto-1.oraclecloudapps.com/ords/fiap/culturas_insumos/

drop table insumos cascade constraints;

create table insumos (
  id number generated by default on null as identity,
  cultura_id number not null,
  nome varchar2(128) not null,
  qtde_ha number not null,
  outras_info varchar2(128),
  constraint insumos_pk primary key (id),
  constraint insumos_fk1 foreign key (cultura_id) references culturas (id) on delete cascade
);

-- endpoint REST => https://g12bbd4aea16cc4-orcl1.adb.ca-toronto-1.oraclecloudapps.com/ords/fiap/insumos/
