
-- Generated by ORDS REST Data Services 24.4.1.r0381713
-- Schema: FIAP  Date: Thu Mar 06 06:55:48 2025 
--
        
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'FIAP',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'fiap',
      p_auto_rest_auth      => FALSE);
    
    
  ORDS.CREATE_ROLE(p_role_name => 'oracle.dbtools.role.autorest.FIAP');
  ORDS.CREATE_ROLE(p_role_name => 'oracle.dbtools.role.autorest.FIAP.SENSOR_LEITURAS');
    
  l_roles(1) := 'oracle.dbtools.autorest.any.schema';
  l_roles(2) := 'oracle.dbtools.role.autorest.FIAP';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'oracle.dbtools.autorest.privilege.FIAP',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'FIAP metadata-catalog access',
      p_description    => 'Provides access to the metadata catalog of the objects in the FIAP schema.',
      p_comments       => NULL); 

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;
    
  l_roles(1) := 'oracle.dbtools.autorest.any.schema';
  l_roles(2) := 'oracle.dbtools.role.autorest.FIAP.SENSOR_LEITURAS';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'oracle.dbtools.autorest.privilege.FIAP.SENSOR_LEITURAS',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'FIAP.SENSOR_LEITURAS access',
      p_description    => 'Provides access to the SENSOR_LEITURAS TABLE in the FIAP schema.',
      p_comments       => NULL); 

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;
    
  l_roles(1) := 'SODA Developer';
  l_patterns(1) := '/soda/*';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'oracle.soda.privilege.developer',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => NULL,
      p_description    => NULL,
      p_comments       => NULL); 

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;
    
  ORDS_METADATA.ORDS.ENABLE_OBJECT(
      p_enabled => TRUE, 
      p_schema => 'FIAP',
      p_object => 'SENSOR_LEITURAS',
      p_object_type => 'TABLE',
      p_object_alias => 'leituras',
      p_auto_rest_auth => FALSE);

          
COMMIT;

END;