CREATE TABLE producao_agricola (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cultura VARCHAR2(100),
    area NUMBER,
    produtividade NUMBER,
    custo NUMBER,
    receita NUMBER
)