-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-10-28 11:44:18 EDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE producao (
    id            NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    id_produto    NUMBER NOT NULL,
    id_uf         VARCHAR2(2) NOT NULL,
    id_safra      NUMBER NOT NULL,
    area_plantada NUMBER NOT NULL,
    qtde_estimada NUMBER NOT NULL,
    qtde_efetiva  NUMBER NOT NULL
);

ALTER TABLE producao ADD CONSTRAINT producao_pk PRIMARY KEY ( id );

CREATE TABLE produto (
    id   NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    nome VARCHAR2(255) NOT NULL
);

ALTER TABLE produto ADD CONSTRAINT produto_pk PRIMARY KEY ( id );

CREATE TABLE regiao (
    id   NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    nome VARCHAR2(255) NOT NULL
);

ALTER TABLE regiao ADD CONSTRAINT regiao_pk PRIMARY KEY ( id );

CREATE TABLE safra (
    id  NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    ano NUMBER NOT NULL,
    mes NUMBER NOT NULL
);

ALTER TABLE safra ADD CONSTRAINT safra_pk PRIMARY KEY ( id );

CREATE TABLE uf (
    id        VARCHAR2(2) NOT NULL,
    id_regiao NUMBER NOT NULL,
    nome      VARCHAR2(255) NOT NULL
);

ALTER TABLE uf ADD CONSTRAINT uf_pk PRIMARY KEY ( id );

ALTER TABLE producao
    ADD CONSTRAINT producao_produto_fk FOREIGN KEY ( id_produto )
        REFERENCES produto ( id );

ALTER TABLE producao
    ADD CONSTRAINT producao_safra_fk FOREIGN KEY ( id_safra )
        REFERENCES safra ( id );

ALTER TABLE producao
    ADD CONSTRAINT producao_uf_fk FOREIGN KEY ( id_uf )
        REFERENCES uf ( id );

ALTER TABLE uf
    ADD CONSTRAINT uf_regiao_fk FOREIGN KEY ( id_regiao )
        REFERENCES regiao ( id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
